import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from './AuthProvider';
import Nav from '@/components/layout/nav';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  if (!process.env.NEXT_PUBLIC_DESCOPE_PROJECT_ID) {
    throw new Error('NEXT_PUBLIC_DESCOPE_PROJECT_ID is not defined');
  }

  return (
    <AuthProvider
      projectId={process.env.NEXT_PUBLIC_DESCOPE_PROJECT_ID}
      baseUrl={process.env.NEXT_PUBLIC_DESCOPE_BASE_URL}
    >
      <html lang="en">
        <body className={inter.className}>
          <Nav />
          <main className="flex min-h-screen w-full flex-col items-center justify-center py-32">
            {children}
          </main>
        </body>
      </html>
    </AuthProvider>
  )
}
